config/routes.rb
Bestcup::Application.routes.draw do
  
  resources :producer_admins

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "totalupdate" => "cupping_total_scores#update", :as => "totalupdate"
  get "totalcreate" => "cupping_total_scores#create", :as => "totalcreate"
  get "dashboard/index"
  get "about" => "dashboard#about", :as => "about"
  
  resources :users, :sessions, :blends, :checks, :farms, :beans, :cupping_total_scores, :cupping_overalls, :cupping_clean_cups, :cupping_uniformities, :cupping_sweetnesses, :cupping_balances, :cupping_mouthfeels, :cupping_acidities, :cupping_after_tastes, :cupping_flavors, :cupping_defects, :cupping_break_aromas, :cupping_crust_aromas, :cupping_dry_fragrances, :cuppings, :roasts, :roasters, :batches, :roastery_admins, :roasteries
  
  root :to => 'dashboard#index'

end

app/models/farm.rb
class Farm < ActiveRecord::Base
  before_validation :downcase_name

  extend FriendlyId
    friendly_id :name, :use => :history
      
  default_scope :order => 'name'
  
  has_many :beans, :dependent => :destroy
  has_many :producer_admins, :dependent => :destroy
  
  validates :name, :country, :presence => true
  
  validates_uniqueness_of :name, :scope => :country, :case_sensitive => false
  
  def is_padmin? (user)
    not producer_admining_for(user).nil?
  end
  
  def producer_admining_for (user)
    producer_admins.find_by_user_id(user)
  end
  
  def name_and_country
    "#{name.titleize} - #{country}"
  end
  
  COUNTRIES = ["Africa", "Australia", "Bali", "Bolivia", "Brazil", "Burundi", "Celebes (Sulawesi)","Central America", "Colombia", "Congo", "Costa Rica", "Dominican Republic", "Ecuador", "El Salvador", "Ethiopia", "Flores", "Guatemala", "Hawaii", "Honduras", "India", "Jamaica", "Java", "Kenya", "Mexico", "Myanmar" "Nicaragua", "Panama", "Papua New Guinea", "Peru", "Puerto Rico", "Rwanda","St Helena","South America", "Sumatra", "Tanzania", "Timor", "Uganda", "Zambia", "Zimbabwe", "", "Angola", "Benin", "Borneo", "Cameroon", "Central African Republic", "Cuba", "Gabon", "Ghana", "Guinea", "Haiti", "Ivory Coast", "Liberia", "Madagascar", "Malawi", "Nigeria", "Panama",  "Paraguay", "Philippines", "Sierra Leone", "Sri Lanka", "Thailand", "Togo", "Trinidad", "Tobago", "Venezuela", "Vietnam", "Yemen", "Zaire",]
  
  private

  def downcase_name
  	self.name = self.name.downcase if self.name.present?
  end
  
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  load_and_authorize_resource

  def index
    @farms = Farm.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @farms }
    end
  end

  def show
    @beans = Bean.where(:farm_id => @farm.id)
    @producer_admin = ProducerAdmin.new
    @producer_admins = ProducerAdmin.where(:farm_id => @farm.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @farm }
    end
  end

  def new
    if params[:batch_id]
      @batch = Batch.find(params[:batch_id])
    end
    if params[:roast_id]
      @roast = Roast.find(params[:roast_id])
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @farm }
    end
  end

  def edit
  end

  def create
    if params[:roast_id]
      @roast = Roast.find(params[:roast_id])
    end
    if params[:batch_id]
      @batch = Batch.find(params[:batch_id])
    end
    respond_to do |format|
      if @farm.save
        if @roast
          format.html { redirect_to new_bean_path(:batch_id => @batch.id, :roast_id => @roast.id, :farm_id => @farm.id), :notice => 'Farm was successfully created.' }
        else
        format.html { redirect_to @farm, :notice => 'Farm was successfully created.' }
        format.json { render :json => @farm, :status => :created, :location => @farm }
        end
      else
        format.html { render :action => "new" }
        format.json { render :json => @farm.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @farm.update_attributes(params[:farm])
        format.html { redirect_to @farm, :notice => 'Farm was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @farm.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @farm.destroy
    respond_to do |format|
      format.html { redirect_to farms_url }
      format.json { head :ok }
    end
  end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_form.html.erb
<section class="section inline clearfix">
	<%= form_for(@farm) do |f| %>
	  <% if @farm.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@farm.errors.count, "error") %> prohibited this farm from being saved:</h2>
	      <ul>
	      <% @farm.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
		<%= f.text_field :name, :placeholder => "of the farm." %>
		<%= f.label :name %>
		<%= f.collection_select :country, Farm::COUNTRIES, :to_s, :to_s, :include_blank => true %>
		<%= f.label :country, "Country" %>
		<%= f.text_field :region, :placeholder => "of the country selected." %>
		<%= f.label :region %>
		<%= f.text_field :farmer, :placeholder => "involved in the farm." %>
		<%= f.label :farmer, "Humans" %>
		<%= f.text_field :elevation, :placeholder => "or elevation's." %>
		<%= f.label :elevation %>
		<%= f.label :description %>
		<%= f.text_area :description, :rows => 5, :placeholder => "The story of the farmers." %>
		<% if params[:roast_id] %>
			<%= hidden_field_tag :roast_id, params[:roast_id] %>
		<% end %>
		<% if params[:batch_id] %>
			<%= hidden_field_tag :batch_id, params[:batch_id] %>
		<% end %>
	  <%= f.submit "Save", :class => "button"  %>
	<% end %>
</section>

app/views/farms/edit.html.erb
<header>
	<h1>Farm</h1>
	<%= link_to 'Back', farm_path(@farm), :class => "button" %>
</header>
	<%= render 'form' %>

app/views/farms/index.html.erb
<header class="clearfix">
	<h1>Farms</h1>
</header>
<% if can? :create, Farm %>
	<%= link_to 'New Farm', new_farm_path , :class => "button" %>
<% end %>
<section class="list">
	<% @farms.each do |farm| %>
		<p>
			<%= link_to farm.name_and_country , farm %>
		</p>
	<% end %>
</section>
<% if current_user.nil? %>
	<footer>
		<nav>
			<div><%= link_to "Log In", root_url %></div>
			<div><%= link_to 'Roasteries', roasteries_url %></div>
			<div><%= link_to 'About', about_path %></div>
		</nav>
	</footer>
<% end %>

app/views/farms/new.html.erb
<% if @batch.present? %>
	<header class="clearfix">
		<h1>Farm</h1>
		<%= link_to "Back", new_bean_path(:batch_id => @batch.id, :roast_id => @roast.id), :class => "button" %>
	</header>
<% else %>
	<header class="clearfix">
		<h1>Farm</h1>
		<%= link_to "Back", farms_path, :class => "button"  %>
	</header>
<% end %>
<%= render 'form' %>

app/views/farms/show.html.erb
<header class="clearfix">
	<h1>Farm</h1>
	<% if can? :create, Bean %>
		<%= link_to "Back", farms_path, :class => "leftbutton" %>
		<%= link_to 'New Bean', new_bean_path(:farm_id => @farm.id), :class => "rightbutton" %>
	<% else %>
		<%= link_to "Back", farms_path, :class => "button" %>
	<% end %>
</header>
<h2><%= @farm.name.titleize %></h2>
<% if @beans.present? %>
	<section class="sectionlist">
		<h2>Beans Produced</h2>
		<section>
			<% @beans.each do |bean| %>
				<p>
					<% if can? :update, bean %>
						<%= link_to 'Edit', edit_bean_path(bean), :class => "redlink"  %>
					<% end %>
					<%= bean.variety %>
					<% if bean.harvest_start.present? or bean.harvest_end.present? %>
						Harvested -
						<% if bean.harvest_start.present? %>
						 	<%= bean.harvest_start %>
						<% end %>
						<% if bean.harvest_end.present? %>
						 	through <%= bean.harvest_end %>
						<% end %>
					<% end %>
				</p>
			<% end %>
		</section>
	</section>
<% end %>
<% if @farm.country.present? || @farm.region.present? || @farm.farmer.present? || @farm.elevation.present? || @farm.description.present? %>
	<section class="section">
		<h2>Details</h2>
			<% if can? :update, @farm %>
				<%= link_to 'Edit', edit_farm_path(@farm), :class => "redlink_section"  %>
			<% end %>
			<% if @farm.country.present? %>
		  	<h2>Country</h2> 
				<p><%= @farm.country %></p>
			<% end %>
			<% if @farm.region.present? %>
		  	<h2>Region</h2> 
				<p><%= @farm.region.titleize %></p>
			<% end %>
			<% if @farm.farmer.present? %>
				<h2>Humans involved</h2> 
				<p><%= @farm.farmer.camelcase %></p>
			<% end %>
			<% if @farm.elevation.present? %>	
			  <h2>Elevation</h2> 
				<p><%= @farm.elevation %></p>
			<% end %>
			<% if @farm.description.present? %>
			  <h2>Description</h2> 
				<p><%= @farm.description.camelcase %></p>
			<% end %>
	</section>
<% else %>
	<% if can? :update, @farm %>
	<section class="clearfix">
		<%= link_to 'Add Details', edit_farm_path(@farm), :class => "redlink_section"  %>
	</section>
	<% end %>
<% end %>

<% if current_user && current_user.admin?  || @farm.is_padmin?(current_user) %>
	<section class="sectionlist">
		<h2>Farm Admins</h2>
		<%= render 'producer_admins/form' %>
		<%= render 'producer_admins/list' %>
	</section>
<% end %>
<% if current_user.nil? %>
	<footer>
		<nav>		
			<div><%= link_to "Log In	", root_url %></div>
			<div><%= link_to 'Roasteries', roasteries_url %></div>
			<div><%= link_to 'About', about_path %></div>
		</nav>
	</footer>
<% end %>