config/routes.rb
Bestcup::Application.routes.draw do
  
  resources :producer_admins

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "totalupdate" => "cupping_total_scores#update", :as => "totalupdate"
  get "totalcreate" => "cupping_total_scores#create", :as => "totalcreate"
  get "dashboard/index"
  get "about" => "dashboard#about", :as => "about"
  
  resources :users, :sessions, :blends, :checks, :farms, :beans, :cupping_total_scores, :cupping_overalls, :cupping_clean_cups, :cupping_uniformities, :cupping_sweetnesses, :cupping_balances, :cupping_mouthfeels, :cupping_acidities, :cupping_after_tastes, :cupping_flavors, :cupping_defects, :cupping_break_aromas, :cupping_crust_aromas, :cupping_dry_fragrances, :cuppings, :roasts, :roasters, :batches, :roastery_admins, :roasteries
  
  root :to => 'dashboard#index'

end

app/models/roastery.rb
class Roastery < ActiveRecord::Base
  before_validation :downcase_name
  
  extend FriendlyId
  friendly_id :name, :use => :history
  
  
  default_scope :order => 'name'
  validates :name,   
            :presence => true,   
            :uniqueness => { :case_sensitive => false }
            
  validates_format_of :website,
                      :allow_blank => true,
                      :with => URI::regexp, 
                      :message => "must start with http://", 
                      :on => :update
  
  has_many :roasts , :dependent => :destroy
  has_many :roastery_admins, :dependent => :destroy
  has_many :roasters, :dependent => :destroy
  has_many :batches, :through => :roasts
  
  def is_roaster? (user)
    not allowed_to_roast(user).nil?
  end
  
  def allowed_to_roast (user)
    roasters.find_by_user_id(user)
  end
  
  def is_radmin? (user)
    not roastery_admining_for(user).nil?
  end
  
  def roastery_admining_for (user)
    roastery_admins.where(:verified => true).find_by_user_id(user)
  end
  
  def get_host_without_www(url)
    url = "http://#{url}" if URI.parse(url).scheme.nil?
    host = URI.parse(url).host.downcase
    host.start_with?('www.') ? host[4..-1] : host
  end

  private

  def downcase_name
    self.name = self.name.downcase if self.name.present?
  end
end

app/controllers/roasteries_controller.rb
class RoasteriesController < ApplicationController
load_and_authorize_resource

  def index
    @roasteries = Roastery.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @roasteries }
    end
  end

  def show
    @roasts = Roast.where(:roastery_id => @roastery.id)
    @blend = Blend.new
    @roastery_admin = RoasteryAdmin.new
    @roastery_admins = RoasteryAdmin.where(:roastery_id => @roastery.id)
    @roaster = Roaster.new
    @roasters = Roaster.where(:roastery_id => @roastery.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @roastery }
    end
    
  end

  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @roastery }
    end
  end

  def edit
  end

  def create
    @user = current_user
    respond_to do |format|
      if @roastery.save
        format.html { redirect_to @roastery, :notice => 'Roastery was successfully created.' }
        format.json { render :json => @roastery, :status => :created, :location => @roastery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @roastery.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @roastery.update_attributes(params[:roastery])
        format.html { redirect_to @roastery, :notice => 'Roastery was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @roastery.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @roastery.destroy
    respond_to do |format|
      format.html { redirect_to roasteries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/roasteries_helper.rb
module RoasteriesHelper
end

app/views/roasteries/_form.html.erb
<section class="section inline clearfix">
	<h2>Details</h2>
	<%= form_for(@roastery) do |f| %>
	  <% if @roastery.errors.any? %>
	  	<div id="error_explanation">
	      <ul>
	      <% @roastery.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
		<%= f.text_field :name, :placeholder => "name." %> 
		<%= f.label :name, "Roastery" %>
		<% if current_user.admin? || @roastery.is_radmin?(current_user) %>
			<%= select_year(Date.today, :start_year => 2011, :end_year => 1835, :prefix => "roastery", :field_name => 'year_opened') %>
			<%= f.label :year_opened %>
			<%= f.url_field :website, :placeholder => "http://" %>
			<%= f.label :website %>
			<%= f.label :description %>
			<%= f.text_area :description, :rows => 5, :placeholder => "The story of the roasters." %>
		<% end %>
	  <%= f.submit "Save", :class => "button"  %>
	<% end %>
</section>

app/views/roasteries/edit.html.erb
<header>
	<h1>Roastery</h1>
	<%= link_to 'Back', roastery_path(@roastery), :class => "button" %>
</header>
<%= render 'form' %>
<!-- <p>
	<%= button_to 'Destroy', @roastery, :confirm => 'Are you sure?', :method => :delete, :class => "button" %>
</p> -->

app/views/roasteries/index.html.erb
<header>
	<h1>Roasteries</h1>
</header>
<% if can? :create, Roastery %>
	<%= link_to 'New Roastery', new_roastery_path, :class => "button"  %>
<% end %>
<section class="list">
	<% @roasteries.each do |roastery| %>
		<p>
			<%= link_to roastery.name.titleize, roastery %>
		</p>
	<% end %>
</section>
<% if current_user.nil? %>
	<footer>
		<nav>
			<div><%= link_to "Log In", root_url %></div>
			<div><%= link_to 'Farms', farms_url %></div>
			<div><%= link_to 'About', about_path %></div>
		</nav>
	</footer>
<% end %>

app/views/roasteries/new.html.erb
<header>
	<h1>Roastery</h1>
	<%= link_to "Back", roasteries_path, :class => "button" %>
</header>
<%= render 'form' %>

app/views/roasteries/show.html.erb
<header>
	<h1>Roastery</h1>
	<% if can? :create, Roast %>
		<%= link_to "Back", roasteries_path, :class => "leftbutton"  %>
		<%= link_to 'New Roast', new_roast_path(:roastery_id => @roastery.id), :class => "rightbutton" %>
	<% else %>
		<%= link_to "Back", roasteries_path, :class => "button" %>
	<% end %>
</header>
<h2><%= @roastery.name.titleize %></h2>
<% if @roasts.present? %>
	<section class="sectionlist">
		<h2>Roasts</h2>
		<section>
		<% @roasts.each do |roast| %>
			<% if can? :read, Roast %>
				<p><%= link_to roast.name.titleize, roast %></p>
			<% else %>
				<p><%= roast.name.titleize %></p>
			<% end %>
		<% end %>
		</section>
	</section>
<% else %>
	<section class="sectionlist">
		<h2>Roasts</h2>
		<section>
			<p>No roasts have been created.</p>
		</section>
	</section>
<% end %>
<% if @roastery.year_opened.present? || @roastery.description.present? || @roastery.website.present? %>
	<section class="section">
		<h2>Details</h2>
		<% if current_user && current_user.admin? || @roastery.is_radmin?(current_user) %>
		<%= link_to 'Edit', edit_roastery_path(@roastery), :class => "redlink_section" %>
		<% end %>
		<% if @roastery.year_opened.present? %>
			<h2>Year opened</h2> 
			<p><%= @roastery.year_opened %></p>
		<% end %>
		<% if @roastery.description.present? %>
		  <h2>Description</h2> 
			<p><%= @roastery.description.camelcase %></p>
		<% end %>
		<% if @roastery.website.present? %>
		  <h2>Website</h2> 
			<p id="weblink"><%= link_to @roastery.get_host_without_www(@roastery.website).camelcase, @roastery.website %></p>
		<% end %>
	</section>
<% else %>
	<% if current_user && current_user.admin? || @roastery.is_radmin?(current_user) %>
	<section class="clearfix">
		<%= link_to 'Add Details', edit_roastery_path(@roastery), :class => "redlink_section" %>
	</section>
	<% end %>
<% end %>
<% if current_user && current_user.admin?  || @roastery.is_radmin?(current_user) %>
	<section class="sectionlist">
			<h2>Roasters</h2>
			<%= render 'roasters/form' %>
			<%= render 'roasters/list' %>
	</section>
	
	
	<section class="sectionlist">
		<h2>Roastery Admins</h2>
		<%= render 'roastery_admins/form' %>
		<%= render 'roastery_admins/list' %>
	</section>
	
	
<% end %>
<% if current_user.nil? %>
	<footer>
		<nav>
			<div><%= link_to "Log In", root_url %></div>
			<div><%= link_to 'Farms', farms_url %></div>
			<div><%= link_to 'About', about_path %></div>
		</nav>
	</footer>
<% end %>