config/routes.rb
Bestcup::Application.routes.draw do
  
  resources :producer_admins

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "totalupdate" => "cupping_total_scores#update", :as => "totalupdate"
  get "totalcreate" => "cupping_total_scores#create", :as => "totalcreate"
  get "dashboard/index"
  get "about" => "dashboard#about", :as => "about"
  
  resources :users, :sessions, :blends, :checks, :farms, :beans, :cupping_total_scores, :cupping_overalls, :cupping_clean_cups, :cupping_uniformities, :cupping_sweetnesses, :cupping_balances, :cupping_mouthfeels, :cupping_acidities, :cupping_after_tastes, :cupping_flavors, :cupping_defects, :cupping_break_aromas, :cupping_crust_aromas, :cupping_dry_fragrances, :cuppings, :roasts, :roasters, :batches, :roastery_admins, :roasteries
  
  root :to => 'dashboard#index'

end

app/models/roast.rb
class Roast < ActiveRecord::Base
  before_validation :downcase_name
  extend FriendlyId
  friendly_id :roastery_roast, :use => :history
  
  default_scope :order => 'name DESC'
  
  validates :name,   
            :presence => true,   
            :uniqueness => { :case_sensitive => false }
  
  belongs_to :roastery
  has_many :batches, :dependent => :destroy
  has_many :blends
  has_many :checks
  has_many :samples
  
  def roast_slelct
    "#{roastery.name}-#{name} | Batch##{batch_number} form #{roasted_on.to_s(:long)}"
  end
  
  def is_radmin? (user)
    not roastery_admining_for(user).nil?
  end
  
  def roastery_admining_for (user)
    roastery.roastery_admins.where(:verified => true).find_by_user_id(user)
  end
  
  def roastery_roast
    "#{roastery.name}-#{name}"
  end
  
  private

  def downcase_name
    self.name = self.name.downcase if self.name.present?
  end
end

app/controllers/roasts_controller.rb
class RoastsController < ApplicationController
  load_and_authorize_resource

  def show
    @roastery = @roast.roastery
    @batches = Batch.where(:roast_id => @roast.id)
    @blend = Blend.new
    @batch = Batch.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @roast }
    end
  end

  def new
    if params[:roastery_id]
      @roastery = Roastery.find(params[:roastery_id])
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @roast }
    end
  end

  def edit
    @roastery = @roast.roastery
  end

  def create
    @roastery = @roast.roastery
    respond_to do |format|
      if @roast.save
        format.html { redirect_to @roast, :notice => 'Roast was successfully created.' }
        format.json { render :json => @roast, :status => :created, :location => @roast }
      else
        format.html { render :action => "new" }
        format.json { render :json => @roast.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @roast.update_attributes(params[:roast])
        format.html { redirect_to @roast, :notice => 'Roast was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @roast.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @roast.destroy
    respond_to do |format|
      format.html { redirect_to @roast.roastery(:roastery_id => @roast.roastery) }
      format.json { head :ok }
    end
  end
end

app/helpers/roasts_helper.rb
module RoastsHelper
end

app/views/roasts/_form.html.erb
<section class="section inline clearfix">
	<%= form_for(@roast) do |f| %>
	  <% if @roast.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@roast.errors.count, "error") %> prohibited this roast from being saved:</h2>
	      <ul>
	      <% @roast.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>	
		<% if @roastery.present? %>
			<%= f.hidden_field :roastery_id, :value => @roastery.id %>
		<% else %>
		  <%= f.collection_select(:roastery_id, Roastery.find(:all), :id, :name, :prompt => true)%> Not on the list? <%= link_to 'New Roastery', new_roastery_path() %>
			<%= f.label :roastery_id %>
		<% end %>	
	  <%= f.text_field :name, :placeholder => "name." %>
		<%= f.label :name, "Roast" %>
	  <% if current_user.admin? || @roastery.is_radmin?(current_user) %>
			<!-- <%= f.label :description %>
			<%= f.text_area :description, :rows => 8, :placeholder => "The story of the Roast."  %> -->
		<% end%>
	  <%= f.submit "Save", :class => "button"  %>
	<% end %>
</section>

app/views/roasts/edit.html.erb
<header>
	<%= link_to 'Back', @roast, :class => "button" %>
</header>
<%= render 'form' %>
<!-- <p>
	<%= button_to 'Destroy', @roast, :confirm => 'Are you sure?', :method => :delete, :class => "button" %>
</p> -->

app/views/roasts/new.html.erb
<header>
	<h1>Roast</h1>
	<%= link_to 'Back', roastery_path(@roastery), :class => "button" %>
</header>
<%= render 'form' %>

app/views/roasts/show.html.erb
<header>
	<h1>Roast</h1>
	<%= link_to "Back", roastery_path(@roastery), :class => "button" %>
</header>
<h2><%= @roast.name.titleize %></h2>
<section class="section">
	<h2>Details</h2>
	<% if current_user && current_user.admin? || @roastery.is_radmin?(current_user) %>
		<%= link_to 'Edit', edit_roast_path(@roast), :class => "redlink_section" %>
	<% end %>	
	<% if @roastery.name.present?%>
		<h2>Roastery</h2>
		<p><%= @roastery.name.titleize %></p>
	<% end %>
	<!-- <% if @roast.description.present?%>
		<h2>Description</h2>
		<p><%= @roast.description.camelcase %></p>
	<% end %>	 -->
</section>
<section class="section batch">
	<h2>New Batch</h2>
	<%= render 'batches/form' %>
</section>
<% if @batches.present? %>
	<% if current_user.admin? || @roastery.is_radmin?(current_user) || @roastery.is_roaster?(current_user) %>
		<section class="sectionlist">
			<h2>Batches</h2>
			<section>
			<% @batches.each do |batch| %>
				<p>
					<%= link_to 'Remove', batch, :confirm => 'Are you sure?', :method => :delete, :class => "removebutton" %><%= link_to batch.roasted_on.to_date.to_formatted_s(:long_ordinal), batch %>Batch #<%= batch.batch_number %>
				</p>
			<% end %>
			</section>
		</section>
	<% else %>
		<section class="sectionlist">
			<h2>Batches</h2>
			<section>
			<% @batches.each do |batch| %>
				<p>
					<%= batch.roasted_on.to_s(:long) %> Batch #<%= batch.batch_number %>
				</p>
			<% end %>
			</section>
		</section>
	<% end %>
<% end %>